// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVOpFLUbK4l0le12Nk2PjH7HUCR6B98Es',
    appId: '1:581496518383:web:ed9e9e5d6a10420e7c8d1a',
    messagingSenderId: '581496518383',
    projectId: 'agri-d6fbb',
    authDomain: 'agri-d6fbb.firebaseapp.com',
    storageBucket: 'agri-d6fbb.firebasestorage.app',
    measurementId: 'G-GD9N9WLHDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJRXvdFJFcwVAfA5AJs_i-SDoqku9WIU',
    appId: '1:581496518383:android:1d8d96c77a8a9aea7c8d1a',
    messagingSenderId: '581496518383',
    projectId: 'agri-d6fbb',
    storageBucket: 'agri-d6fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDT_5Xg1Jzf3wqQyX-kAUqDCWB0cN7C2Y',
    appId: '1:581496518383:ios:8aeeafbfa8713eff7c8d1a',
    messagingSenderId: '581496518383',
    projectId: 'agri-d6fbb',
    storageBucket: 'agri-d6fbb.firebasestorage.app',
    iosBundleId: 'com.example.agriFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDT_5Xg1Jzf3wqQyX-kAUqDCWB0cN7C2Y',
    appId: '1:581496518383:ios:8aeeafbfa8713eff7c8d1a',
    messagingSenderId: '581496518383',
    projectId: 'agri-d6fbb',
    storageBucket: 'agri-d6fbb.firebasestorage.app',
    iosBundleId: 'com.example.agriFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVOpFLUbK4l0le12Nk2PjH7HUCR6B98Es',
    appId: '1:581496518383:web:4bd66152085fd3c07c8d1a',
    messagingSenderId: '581496518383',
    projectId: 'agri-d6fbb',
    authDomain: 'agri-d6fbb.firebaseapp.com',
    storageBucket: 'agri-d6fbb.firebasestorage.app',
    measurementId: 'G-RRF74RTXTE',
  );

}